### ISSUE TITLE
Add script for USD

### ISSUE THREAD

**Issue by daseyb** [meshula/mkvfx#11]
Hi, I just came across this project, I think it's a great idea!
[USD](https://github.com/PixarAnimationStudios/USD) was recently open sourced and I've already spent about 5 hours on Windows trying to get it to build. Considering the number of dependencies, I think it would be a good candidate for mkvfx.

I might work on a script myself in a couple of weeks, but unfortunately I'm in the middle of writing exams right now. :)

**Comment by meshula** [comment]
usd-build-club is pretty stable now, as is the official Pixar build script.
