### ISSUE TITLE
"mkvfx knows how to build:" erroring out on print (windows)

### ISSUE THREAD

**Issue by talonrenaud** [meshula/mkvfx#5]
Hi !
I was getting the following error when running mkvfx.py on windows:
```None
mkvfx knows how to build:

Traceback (most recent call last):
  File "C:\mkvfx\mkvfx.py", line 489, in <module>
    print_help()
  File "C:\mkvfx\mkvfx.py", line 48, in print_help
    print ' ', p["name"]
TypeError: string indices must be integers
```

I made the following changes to get it to run properly:
```python
def print_help():
    global package_recipes, build_platform
    print "mkvfx knows how to build:"
    for p in package_recipes:
        if package_recipes[p]["platforms"]:
            if build_platform in package_recipes[p]["platforms"]:
                print ' ', package_recipes[p]['name']
        else:
            print ' ', package_recipes[p]['name']
    print "\nNote that git repos are shallow cloned.\n"
```
On a different note I'm extremely interested in getting OpenImageIO and OpenColorIO for MSVS2015.
I attempted to compile them several times now but didn't succeed. Did you have any luck on the matter ?

Thanks for the initiative and sharing this is an extremely useful effort.

**Comment by meshula** [comment]
Thanks for the patch!

https://github.com/meshula/mkvfx/commit/b4e01b48be71da09003ef3f5767487173dbd0adf

OIIO and OCIO are both tricky for msvc. Nothing ready yet. I added issues 7, 8, and 9.
