### ISSUE TITLE
Premake "detection" doesn't seem to work on windows 10

### ISSUE THREAD

**Issue by talonrenaud** [meshula/mkvfx#6]
When I run mkvfx.py the script doesn't seem to detect premake4 and 5 properly.
Both executables are set in my path (env. varaibles) and the script even outputs: "premakeX -- version" properly, see output below.

```
Running premake4 --version
premake4 (Premake Build Script Generator) 4.4-beta5
Running premake5 --version
premake5 (Premake Build Script Generator) 5.0.0-alpha7
MKVFX could not find premake4 and/or 5, please install them and try again
```

Thanks,
Renaud

**Comment by meshula** [comment]
Can you try again from this commit?

https://github.com/meshula/mkvfx/commit/2801b9037bd16f1d109440767379ad6dac5c594a

I get the following output (on Windows 10) with premake4 missing, but premake5 installed:

Running premake4 --version
'premake4' is not recognized as an internal or external command,
operable program or batch file.
Running premake5 --version
premake5 (Premake Build Script Generator) 5.0.0-alpha7
MKVFX could not find premake4. Build steps requiring premake4 will fail.

**Comment by talonrenaud** [comment]
The problem seems to persist after I pulled your latest commit. See attached screenshot.
![mkvfx](https://cloud.githubusercontent.com/assets/6299536/12542918/4b88a18e-c2de-11e5-99d0-bbb26362dc49.jpg)

**Comment by talonrenaud** [comment]
I'm in the process of re-installing my machine so please ignore the 7zip error. I didn't installed yet.

**Comment by meshula** [comment]
premake4 returns a different value for success than premake5. Uggh.

https://github.com/meshula/mkvfx/commit/f4791c8d8607c48d76c61e6e30e26a0ec1c9c81a

This should work.

**Comment by meshula** [comment]
@talonrenaud Did you have a chance to try again?

**Comment by meshula** [comment]
Please reopen if this is still an issue.
